export const POSITIVE_NUMBER_PATTERN = '^[0-9]+$'
export const ROLE_NAME_PATTERN = '^[a-zA-Z][a-zA-Z0-9]+ ?[a-zA-Z0-9]+$'
export const UUID_PATTERN = '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
export const EMAIL_PATTERN = '^[^ @]+@[^ @]+\.[^ @]+$'
export const PASSWORD_PATTERN = '^[^ ]{8,16}$'
